// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analytics.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLeaderboard = `-- name: CreateLeaderboard :one
INSERT INTO leaderboards (
  batch_id, week_start, week_end
) VALUES (
  $1, $2, $3
)
RETURNING id, batch_id, week_start, week_end, created_at
`

type CreateLeaderboardParams struct {
	BatchID   pgtype.UUID        `json:"batch_id"`
	WeekStart pgtype.Timestamptz `json:"week_start"`
	WeekEnd   pgtype.Timestamptz `json:"week_end"`
}

func (q *Queries) CreateLeaderboard(ctx context.Context, arg CreateLeaderboardParams) (Leaderboard, error) {
	row := q.db.QueryRow(ctx, createLeaderboard, arg.BatchID, arg.WeekStart, arg.WeekEnd)
	var i Leaderboard
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.WeekStart,
		&i.WeekEnd,
		&i.CreatedAt,
	)
	return i, err
}

const getLeaderboard = `-- name: GetLeaderboard :one
SELECT id, batch_id, week_start, week_end, created_at FROM leaderboards
WHERE batch_id = $1 AND week_start = $2 AND week_end = $3 LIMIT 1
`

type GetLeaderboardParams struct {
	BatchID   pgtype.UUID        `json:"batch_id"`
	WeekStart pgtype.Timestamptz `json:"week_start"`
	WeekEnd   pgtype.Timestamptz `json:"week_end"`
}

func (q *Queries) GetLeaderboard(ctx context.Context, arg GetLeaderboardParams) (Leaderboard, error) {
	row := q.db.QueryRow(ctx, getLeaderboard, arg.BatchID, arg.WeekStart, arg.WeekEnd)
	var i Leaderboard
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.WeekStart,
		&i.WeekEnd,
		&i.CreatedAt,
	)
	return i, err
}

const getLeaderboardEntries = `-- name: GetLeaderboardEntries :many
SELECT 
  e.id, e.leaderboard_id, e.mentee_id, e.score, e.rank,
  u.name as mentee_name,
  u.avatar_url as mentee_avatar
FROM leaderboard_entries e
JOIN user_profiles u ON e.mentee_id = u.user_id
WHERE e.leaderboard_id = $1
ORDER BY e.score DESC, e.rank ASC
`

type GetLeaderboardEntriesRow struct {
	ID            pgtype.UUID `json:"id"`
	LeaderboardID pgtype.UUID `json:"leaderboard_id"`
	MenteeID      pgtype.UUID `json:"mentee_id"`
	Score         int32       `json:"score"`
	Rank          *int32      `json:"rank"`
	MenteeName    string      `json:"mentee_name"`
	MenteeAvatar  *string     `json:"mentee_avatar"`
}

func (q *Queries) GetLeaderboardEntries(ctx context.Context, leaderboardID pgtype.UUID) ([]GetLeaderboardEntriesRow, error) {
	rows, err := q.db.Query(ctx, getLeaderboardEntries, leaderboardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLeaderboardEntriesRow
	for rows.Next() {
		var i GetLeaderboardEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.LeaderboardID,
			&i.MenteeID,
			&i.Score,
			&i.Rank,
			&i.MenteeName,
			&i.MenteeAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMenteeAnalytics = `-- name: GetMenteeAnalytics :one
SELECT 
  COUNT(t.id) as total_tasks,
  SUM(CASE WHEN t.status = 'completed' THEN 1 ELSE 0 END) as completed_tasks,
  SUM(CASE WHEN t.status = 'doubt' THEN 1 ELSE 0 END) as doubt_tasks
FROM assignment_tasks t
JOIN assignments a ON t.assignment_id = a.id
WHERE a.mentee_id = $1
`

type GetMenteeAnalyticsRow struct {
	TotalTasks     int64 `json:"total_tasks"`
	CompletedTasks int64 `json:"completed_tasks"`
	DoubtTasks     int64 `json:"doubt_tasks"`
}

func (q *Queries) GetMenteeAnalytics(ctx context.Context, menteeID pgtype.UUID) (GetMenteeAnalyticsRow, error) {
	row := q.db.QueryRow(ctx, getMenteeAnalytics, menteeID)
	var i GetMenteeAnalyticsRow
	err := row.Scan(&i.TotalTasks, &i.CompletedTasks, &i.DoubtTasks)
	return i, err
}

const upsertLeaderboardEntry = `-- name: UpsertLeaderboardEntry :exec
INSERT INTO leaderboard_entries (
  leaderboard_id, mentee_id, score, rank
) VALUES (
  $1, $2, $3, $4
) ON CONFLICT (leaderboard_id, mentee_id) DO UPDATE
SET score = EXCLUDED.score,
    rank = EXCLUDED.rank
`

type UpsertLeaderboardEntryParams struct {
	LeaderboardID pgtype.UUID `json:"leaderboard_id"`
	MenteeID      pgtype.UUID `json:"mentee_id"`
	Score         int32       `json:"score"`
	Rank          *int32      `json:"rank"`
}

func (q *Queries) UpsertLeaderboardEntry(ctx context.Context, arg UpsertLeaderboardEntryParams) error {
	_, err := q.db.Exec(ctx, upsertLeaderboardEntry,
		arg.LeaderboardID,
		arg.MenteeID,
		arg.Score,
		arg.Rank,
	)
	return err
}
