// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assignments.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAssignment = `-- name: CreateAssignment :one
INSERT INTO assignments (
  mentee_id, title, start_date, deadline, status
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, mentee_id, title, start_date, deadline, status, created_at
`

type CreateAssignmentParams struct {
	MenteeID  pgtype.UUID          `json:"mentee_id"`
	Title     string               `json:"title"`
	StartDate pgtype.Timestamptz   `json:"start_date"`
	Deadline  pgtype.Timestamptz   `json:"deadline"`
	Status    NullAssignmentStatus `json:"status"`
}

func (q *Queries) CreateAssignment(ctx context.Context, arg CreateAssignmentParams) (Assignment, error) {
	row := q.db.QueryRow(ctx, createAssignment,
		arg.MenteeID,
		arg.Title,
		arg.StartDate,
		arg.Deadline,
		arg.Status,
	)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.MenteeID,
		&i.Title,
		&i.StartDate,
		&i.Deadline,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createAssignmentTask = `-- name: CreateAssignmentTask :one
INSERT INTO assignment_tasks (
  assignment_id, question_id, status, assigned_by
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, assignment_id, question_id, status, assigned_by, created_at
`

type CreateAssignmentTaskParams struct {
	AssignmentID pgtype.UUID    `json:"assignment_id"`
	QuestionID   pgtype.UUID    `json:"question_id"`
	Status       NullTaskStatus `json:"status"`
	AssignedBy   pgtype.UUID    `json:"assigned_by"`
}

func (q *Queries) CreateAssignmentTask(ctx context.Context, arg CreateAssignmentTaskParams) (AssignmentTask, error) {
	row := q.db.QueryRow(ctx, createAssignmentTask,
		arg.AssignmentID,
		arg.QuestionID,
		arg.Status,
		arg.AssignedBy,
	)
	var i AssignmentTask
	err := row.Scan(
		&i.ID,
		&i.AssignmentID,
		&i.QuestionID,
		&i.Status,
		&i.AssignedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getAssignmentByID = `-- name: GetAssignmentByID :one
SELECT id, mentee_id, title, start_date, deadline, status, created_at FROM assignments
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAssignmentByID(ctx context.Context, id pgtype.UUID) (Assignment, error) {
	row := q.db.QueryRow(ctx, getAssignmentByID, id)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.MenteeID,
		&i.Title,
		&i.StartDate,
		&i.Deadline,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getTasksForAssignment = `-- name: GetTasksForAssignment :many
SELECT 
  t.id as task_id,
  t.assignment_id,
  t.status as task_status,
  q.id as question_id,
  q.title as question_title,
  q.difficulty as question_difficulty
FROM assignment_tasks t
JOIN questions q ON t.question_id = q.id
WHERE t.assignment_id = $1
ORDER BY t.created_at ASC
`

type GetTasksForAssignmentRow struct {
	TaskID             pgtype.UUID     `json:"task_id"`
	AssignmentID       pgtype.UUID     `json:"assignment_id"`
	TaskStatus         NullTaskStatus  `json:"task_status"`
	QuestionID         pgtype.UUID     `json:"question_id"`
	QuestionTitle      string          `json:"question_title"`
	QuestionDifficulty DifficultyLevel `json:"question_difficulty"`
}

func (q *Queries) GetTasksForAssignment(ctx context.Context, assignmentID pgtype.UUID) ([]GetTasksForAssignmentRow, error) {
	rows, err := q.db.Query(ctx, getTasksForAssignment, assignmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTasksForAssignmentRow
	for rows.Next() {
		var i GetTasksForAssignmentRow
		if err := rows.Scan(
			&i.TaskID,
			&i.AssignmentID,
			&i.TaskStatus,
			&i.QuestionID,
			&i.QuestionTitle,
			&i.QuestionDifficulty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssignmentsByMentee = `-- name: ListAssignmentsByMentee :many
SELECT id, mentee_id, title, start_date, deadline, status, created_at FROM assignments
WHERE mentee_id = $1
ORDER BY start_date DESC
LIMIT $2 OFFSET $3
`

type ListAssignmentsByMenteeParams struct {
	MenteeID pgtype.UUID `json:"mentee_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListAssignmentsByMentee(ctx context.Context, arg ListAssignmentsByMenteeParams) ([]Assignment, error) {
	rows, err := q.db.Query(ctx, listAssignmentsByMentee, arg.MenteeID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Assignment
	for rows.Next() {
		var i Assignment
		if err := rows.Scan(
			&i.ID,
			&i.MenteeID,
			&i.Title,
			&i.StartDate,
			&i.Deadline,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAssignmentStatus = `-- name: UpdateAssignmentStatus :exec
UPDATE assignments
SET status = $2
WHERE id = $1
`

type UpdateAssignmentStatusParams struct {
	ID     pgtype.UUID          `json:"id"`
	Status NullAssignmentStatus `json:"status"`
}

func (q *Queries) UpdateAssignmentStatus(ctx context.Context, arg UpdateAssignmentStatusParams) error {
	_, err := q.db.Exec(ctx, updateAssignmentStatus, arg.ID, arg.Status)
	return err
}

const updateTaskStatus = `-- name: UpdateTaskStatus :exec
UPDATE assignment_tasks
SET status = $2
WHERE id = $1
`

type UpdateTaskStatusParams struct {
	ID     pgtype.UUID    `json:"id"`
	Status NullTaskStatus `json:"status"`
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) error {
	_, err := q.db.Exec(ctx, updateTaskStatus, arg.ID, arg.Status)
	return err
}
