// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AssignmentStatus string

const (
	AssignmentStatusActive    AssignmentStatus = "active"
	AssignmentStatusCompleted AssignmentStatus = "completed"
	AssignmentStatusOverdue   AssignmentStatus = "overdue"
)

func (e *AssignmentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AssignmentStatus(s)
	case string:
		*e = AssignmentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AssignmentStatus: %T", src)
	}
	return nil
}

type NullAssignmentStatus struct {
	AssignmentStatus AssignmentStatus `json:"assignment_status"`
	Valid            bool             `json:"valid"` // Valid is true if AssignmentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAssignmentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AssignmentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AssignmentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAssignmentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AssignmentStatus), nil
}

type DifficultyLevel string

const (
	DifficultyLevelEasy   DifficultyLevel = "easy"
	DifficultyLevelMedium DifficultyLevel = "medium"
	DifficultyLevelHard   DifficultyLevel = "hard"
)

func (e *DifficultyLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DifficultyLevel(s)
	case string:
		*e = DifficultyLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for DifficultyLevel: %T", src)
	}
	return nil
}

type NullDifficultyLevel struct {
	DifficultyLevel DifficultyLevel `json:"difficulty_level"`
	Valid           bool            `json:"valid"` // Valid is true if DifficultyLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDifficultyLevel) Scan(value interface{}) error {
	if value == nil {
		ns.DifficultyLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DifficultyLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDifficultyLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DifficultyLevel), nil
}

type DoubtStatus string

const (
	DoubtStatusOpen     DoubtStatus = "open"
	DoubtStatusResolved DoubtStatus = "resolved"
)

func (e *DoubtStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DoubtStatus(s)
	case string:
		*e = DoubtStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DoubtStatus: %T", src)
	}
	return nil
}

type NullDoubtStatus struct {
	DoubtStatus DoubtStatus `json:"doubt_status"`
	Valid       bool        `json:"valid"` // Valid is true if DoubtStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDoubtStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DoubtStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DoubtStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDoubtStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DoubtStatus), nil
}

type SubmissionStatus string

const (
	SubmissionStatusSubmitted      SubmissionStatus = "submitted"
	SubmissionStatusReviewed       SubmissionStatus = "reviewed"
	SubmissionStatusRevisionNeeded SubmissionStatus = "revision_needed"
)

func (e *SubmissionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SubmissionStatus(s)
	case string:
		*e = SubmissionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SubmissionStatus: %T", src)
	}
	return nil
}

type NullSubmissionStatus struct {
	SubmissionStatus SubmissionStatus `json:"submission_status"`
	Valid            bool             `json:"valid"` // Valid is true if SubmissionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSubmissionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SubmissionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SubmissionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSubmissionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SubmissionStatus), nil
}

type TaskStatus string

const (
	TaskStatusPending   TaskStatus = "pending"
	TaskStatusCompleted TaskStatus = "completed"
	TaskStatusDoubt     TaskStatus = "doubt"
)

func (e *TaskStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskStatus(s)
	case string:
		*e = TaskStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskStatus: %T", src)
	}
	return nil
}

type NullTaskStatus struct {
	TaskStatus TaskStatus `json:"task_status"`
	Valid      bool       `json:"valid"` // Valid is true if TaskStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TaskStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskStatus), nil
}

type UserRole string

const (
	UserRoleMentor UserRole = "mentor"
	UserRoleMentee UserRole = "mentee"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Assignment struct {
	ID        pgtype.UUID          `json:"id"`
	MenteeID  pgtype.UUID          `json:"mentee_id"`
	Title     string               `json:"title"`
	StartDate pgtype.Timestamptz   `json:"start_date"`
	Deadline  pgtype.Timestamptz   `json:"deadline"`
	Status    NullAssignmentStatus `json:"status"`
	CreatedAt pgtype.Timestamptz   `json:"created_at"`
}

type AssignmentTask struct {
	ID           pgtype.UUID        `json:"id"`
	AssignmentID pgtype.UUID        `json:"assignment_id"`
	QuestionID   pgtype.UUID        `json:"question_id"`
	Status       NullTaskStatus     `json:"status"`
	AssignedBy   pgtype.UUID        `json:"assigned_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Batch struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	MentorID  pgtype.UUID        `json:"mentor_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type BatchMentee struct {
	BatchID  pgtype.UUID        `json:"batch_id"`
	MenteeID pgtype.UUID        `json:"mentee_id"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

type Doubt struct {
	ID               pgtype.UUID        `json:"id"`
	AssignmentTaskID pgtype.UUID        `json:"assignment_task_id"`
	MenteeID         pgtype.UUID        `json:"mentee_id"`
	Status           NullDoubtStatus    `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type DoubtThread struct {
	ID        pgtype.UUID        `json:"id"`
	DoubtID   pgtype.UUID        `json:"doubt_id"`
	SenderID  pgtype.UUID        `json:"sender_id"`
	Message   string             `json:"message"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Hint struct {
	ID           pgtype.UUID `json:"id"`
	QuestionID   pgtype.UUID `json:"question_id"`
	Content      string      `json:"content"`
	DisplayOrder int32       `json:"display_order"`
}

type Leaderboard struct {
	ID        pgtype.UUID        `json:"id"`
	BatchID   pgtype.UUID        `json:"batch_id"`
	WeekStart pgtype.Timestamptz `json:"week_start"`
	WeekEnd   pgtype.Timestamptz `json:"week_end"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type LeaderboardEntry struct {
	ID            pgtype.UUID `json:"id"`
	LeaderboardID pgtype.UUID `json:"leaderboard_id"`
	MenteeID      pgtype.UUID `json:"mentee_id"`
	Score         int32       `json:"score"`
	Rank          *int32      `json:"rank"`
}

type MentorFeedback struct {
	ID               pgtype.UUID        `json:"id"`
	SubmissionID     pgtype.UUID        `json:"submission_id"`
	MentorID         pgtype.UUID        `json:"mentor_id"`
	Comment          string             `json:"comment"`
	RevisionRequired *bool              `json:"revision_required"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type Poll struct {
	ID        pgtype.UUID        `json:"id"`
	BatchID   pgtype.UUID        `json:"batch_id"`
	MentorID  pgtype.UUID        `json:"mentor_id"`
	Question  string             `json:"question"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PollOption struct {
	ID     pgtype.UUID `json:"id"`
	PollID pgtype.UUID `json:"poll_id"`
	Text   string      `json:"text"`
}

type PollVote struct {
	ID           pgtype.UUID `json:"id"`
	PollOptionID pgtype.UUID `json:"poll_option_id"`
	MenteeID     pgtype.UUID `json:"mentee_id"`
}

type Question struct {
	ID              pgtype.UUID        `json:"id"`
	Title           string             `json:"title"`
	ContentMarkdown string             `json:"content_markdown"`
	Difficulty      DifficultyLevel    `json:"difficulty"`
	Topic           string             `json:"topic"`
	ExternalLink    *string            `json:"external_link"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type Submission struct {
	ID               pgtype.UUID          `json:"id"`
	AssignmentTaskID pgtype.UUID          `json:"assignment_task_id"`
	MenteeID         pgtype.UUID          `json:"mentee_id"`
	SolutionUrl      string               `json:"solution_url"`
	Status           NullSubmissionStatus `json:"status"`
	SubmittedAt      pgtype.Timestamptz   `json:"submitted_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         UserRole           `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type UserProfile struct {
	UserID    pgtype.UUID `json:"user_id"`
	Name      string      `json:"name"`
	AvatarUrl *string     `json:"avatar_url"`
	Bio       *string     `json:"bio"`
}
