// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddHint(ctx context.Context, arg AddHintParams) (Hint, error)
	AddMenteeToBatch(ctx context.Context, arg AddMenteeToBatchParams) error
	CreateAssignment(ctx context.Context, arg CreateAssignmentParams) (Assignment, error)
	CreateAssignmentTask(ctx context.Context, arg CreateAssignmentTaskParams) (AssignmentTask, error)
	CreateBatch(ctx context.Context, arg CreateBatchParams) (Batch, error)
	CreateFeedback(ctx context.Context, arg CreateFeedbackParams) (MentorFeedback, error)
	CreateLeaderboard(ctx context.Context, arg CreateLeaderboardParams) (Leaderboard, error)
	CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error)
	CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (Submission, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) (UserProfile, error)
	GetAssignmentByID(ctx context.Context, id pgtype.UUID) (Assignment, error)
	GetFeedbackBySubmission(ctx context.Context, submissionID pgtype.UUID) (MentorFeedback, error)
	GetHintsForQuestion(ctx context.Context, questionID pgtype.UUID) ([]Hint, error)
	GetLeaderboard(ctx context.Context, arg GetLeaderboardParams) (Leaderboard, error)
	GetLeaderboardEntries(ctx context.Context, leaderboardID pgtype.UUID) ([]GetLeaderboardEntriesRow, error)
	GetMenteeAnalytics(ctx context.Context, menteeID pgtype.UUID) (GetMenteeAnalyticsRow, error)
	GetQuestionByID(ctx context.Context, id pgtype.UUID) (Question, error)
	GetRecentActivity(ctx context.Context, limit int32) ([]GetRecentActivityRow, error)
	GetSubmissionByID(ctx context.Context, id pgtype.UUID) (Submission, error)
	GetSubmissionsForTask(ctx context.Context, assignmentTaskID pgtype.UUID) ([]Submission, error)
	GetTasksForAssignment(ctx context.Context, assignmentID pgtype.UUID) ([]GetTasksForAssignmentRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserProfile(ctx context.Context, userID pgtype.UUID) (UserProfile, error)
	ListAssignmentsByMentee(ctx context.Context, arg ListAssignmentsByMenteeParams) ([]Assignment, error)
	ListQuestions(ctx context.Context, arg ListQuestionsParams) ([]Question, error)
	UpdateAssignmentStatus(ctx context.Context, arg UpdateAssignmentStatusParams) error
	UpdateSubmissionStatus(ctx context.Context, arg UpdateSubmissionStatusParams) error
	UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) error
	UpsertLeaderboardEntry(ctx context.Context, arg UpsertLeaderboardEntryParams) error
	ListSubmissionsWithDetailsByAssignment(ctx context.Context, assignmentID pgtype.UUID) ([]SubmissionDetailRow, error)
	ListUsersByRole(ctx context.Context, role UserRole) ([]UserWithProfileRow, error)
}

var _ Querier = (*Queries)(nil)
