// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: questions.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addHint = `-- name: AddHint :one
INSERT INTO hints (
  question_id, content, display_order
) VALUES (
  $1, $2, $3
)
RETURNING id, question_id, content, display_order
`

type AddHintParams struct {
	QuestionID   pgtype.UUID `json:"question_id"`
	Content      string      `json:"content"`
	DisplayOrder int32       `json:"display_order"`
}

func (q *Queries) AddHint(ctx context.Context, arg AddHintParams) (Hint, error) {
	row := q.db.QueryRow(ctx, addHint, arg.QuestionID, arg.Content, arg.DisplayOrder)
	var i Hint
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.Content,
		&i.DisplayOrder,
	)
	return i, err
}

const createQuestion = `-- name: CreateQuestion :one
INSERT INTO questions (
  title, content_markdown, difficulty, topic, external_link, created_by
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id, title, content_markdown, difficulty, topic, external_link, created_by, created_at, deleted_at
`

type CreateQuestionParams struct {
	Title           string          `json:"title"`
	ContentMarkdown string          `json:"content_markdown"`
	Difficulty      DifficultyLevel `json:"difficulty"`
	Topic           string          `json:"topic"`
	ExternalLink    *string         `json:"external_link"`
	CreatedBy       pgtype.UUID     `json:"created_by"`
}

func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error) {
	row := q.db.QueryRow(ctx, createQuestion,
		arg.Title,
		arg.ContentMarkdown,
		arg.Difficulty,
		arg.Topic,
		arg.ExternalLink,
		arg.CreatedBy,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ContentMarkdown,
		&i.Difficulty,
		&i.Topic,
		&i.ExternalLink,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getHintsForQuestion = `-- name: GetHintsForQuestion :many
SELECT id, question_id, content, display_order FROM hints
WHERE question_id = $1
ORDER BY display_order ASC
`

func (q *Queries) GetHintsForQuestion(ctx context.Context, questionID pgtype.UUID) ([]Hint, error) {
	rows, err := q.db.Query(ctx, getHintsForQuestion, questionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Hint
	for rows.Next() {
		var i Hint
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.Content,
			&i.DisplayOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQuestionByID = `-- name: GetQuestionByID :one
SELECT id, title, content_markdown, difficulty, topic, external_link, created_by, created_at, deleted_at FROM questions
WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetQuestionByID(ctx context.Context, id pgtype.UUID) (Question, error) {
	row := q.db.QueryRow(ctx, getQuestionByID, id)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ContentMarkdown,
		&i.Difficulty,
		&i.Topic,
		&i.ExternalLink,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listQuestions = `-- name: ListQuestions :many
SELECT id, title, content_markdown, difficulty, topic, external_link, created_by, created_at, deleted_at FROM questions
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListQuestionsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListQuestions(ctx context.Context, arg ListQuestionsParams) ([]Question, error) {
	rows, err := q.db.Query(ctx, listQuestions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Question
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ContentMarkdown,
			&i.Difficulty,
			&i.Topic,
			&i.ExternalLink,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
