// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: submissions.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFeedback = `-- name: CreateFeedback :one
INSERT INTO mentor_feedbacks (
  submission_id, mentor_id, comment, revision_required
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, submission_id, mentor_id, comment, revision_required, created_at
`

type CreateFeedbackParams struct {
	SubmissionID     pgtype.UUID `json:"submission_id"`
	MentorID         pgtype.UUID `json:"mentor_id"`
	Comment          string      `json:"comment"`
	RevisionRequired *bool       `json:"revision_required"`
}

func (q *Queries) CreateFeedback(ctx context.Context, arg CreateFeedbackParams) (MentorFeedback, error) {
	row := q.db.QueryRow(ctx, createFeedback,
		arg.SubmissionID,
		arg.MentorID,
		arg.Comment,
		arg.RevisionRequired,
	)
	var i MentorFeedback
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.MentorID,
		&i.Comment,
		&i.RevisionRequired,
		&i.CreatedAt,
	)
	return i, err
}

const createSubmission = `-- name: CreateSubmission :one
INSERT INTO submissions (
  assignment_task_id, mentee_id, solution_url, status
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, assignment_task_id, mentee_id, solution_url, status, submitted_at
`

type CreateSubmissionParams struct {
	AssignmentTaskID pgtype.UUID          `json:"assignment_task_id"`
	MenteeID         pgtype.UUID          `json:"mentee_id"`
	SolutionUrl      string               `json:"solution_url"`
	Status           NullSubmissionStatus `json:"status"`
}

func (q *Queries) CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (Submission, error) {
	row := q.db.QueryRow(ctx, createSubmission,
		arg.AssignmentTaskID,
		arg.MenteeID,
		arg.SolutionUrl,
		arg.Status,
	)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.AssignmentTaskID,
		&i.MenteeID,
		&i.SolutionUrl,
		&i.Status,
		&i.SubmittedAt,
	)
	return i, err
}

const getFeedbackBySubmission = `-- name: GetFeedbackBySubmission :one
SELECT id, submission_id, mentor_id, comment, revision_required, created_at FROM mentor_feedbacks
WHERE submission_id = $1 LIMIT 1
`

func (q *Queries) GetFeedbackBySubmission(ctx context.Context, submissionID pgtype.UUID) (MentorFeedback, error) {
	row := q.db.QueryRow(ctx, getFeedbackBySubmission, submissionID)
	var i MentorFeedback
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.MentorID,
		&i.Comment,
		&i.RevisionRequired,
		&i.CreatedAt,
	)
	return i, err
}

const getRecentActivity = `-- name: GetRecentActivity :many
SELECT 
  s.id as submission_id,
  s.mentee_id,
  COALESCE(u.name, users.email) as mentee_name,
  s.solution_url,
  s.status as submission_status,
  s.submitted_at,
  q.title as question_title,
  t.id as task_id
FROM submissions s
JOIN users ON s.mentee_id = users.id
LEFT JOIN user_profiles u ON s.mentee_id = u.user_id
JOIN assignment_tasks t ON s.assignment_task_id = t.id
JOIN questions q ON t.question_id = q.id
ORDER BY s.submitted_at DESC
LIMIT $1
`

type GetRecentActivityRow struct {
	SubmissionID     pgtype.UUID          `json:"submission_id"`
	MenteeID         pgtype.UUID          `json:"mentee_id"`
	MenteeName       string               `json:"mentee_name"`
	SolutionUrl      *string              `json:"solution_url"`
	SubmissionStatus NullSubmissionStatus `json:"submission_status"`
	SubmittedAt      pgtype.Timestamptz   `json:"submitted_at"`
	QuestionTitle    string               `json:"question_title"`
	TaskID           pgtype.UUID          `json:"task_id"`
}

func (q *Queries) GetRecentActivity(ctx context.Context, limit int32) ([]GetRecentActivityRow, error) {
	rows, err := q.db.Query(ctx, getRecentActivity, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentActivityRow
	for rows.Next() {
		var i GetRecentActivityRow
		if err := rows.Scan(
			&i.SubmissionID,
			&i.MenteeID,
			&i.MenteeName,
			&i.SolutionUrl,
			&i.SubmissionStatus,
			&i.SubmittedAt,
			&i.QuestionTitle,
			&i.TaskID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubmissionByID = `-- name: GetSubmissionByID :one
SELECT id, assignment_task_id, mentee_id, solution_url, status, submitted_at FROM submissions
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSubmissionByID(ctx context.Context, id pgtype.UUID) (Submission, error) {
	row := q.db.QueryRow(ctx, getSubmissionByID, id)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.AssignmentTaskID,
		&i.MenteeID,
		&i.SolutionUrl,
		&i.Status,
		&i.SubmittedAt,
	)
	return i, err
}

const getSubmissionsForTask = `-- name: GetSubmissionsForTask :many
SELECT id, assignment_task_id, mentee_id, solution_url, status, submitted_at FROM submissions
WHERE assignment_task_id = $1
ORDER BY submitted_at DESC
`

func (q *Queries) GetSubmissionsForTask(ctx context.Context, assignmentTaskID pgtype.UUID) ([]Submission, error) {
	rows, err := q.db.Query(ctx, getSubmissionsForTask, assignmentTaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Submission
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.ID,
			&i.AssignmentTaskID,
			&i.MenteeID,
			&i.SolutionUrl,
			&i.Status,
			&i.SubmittedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubmissionStatus = `-- name: UpdateSubmissionStatus :exec
UPDATE submissions
SET status = $2
WHERE id = $1
`

type UpdateSubmissionStatusParams struct {
	ID     pgtype.UUID          `json:"id"`
	Status NullSubmissionStatus `json:"status"`
}

func (q *Queries) UpdateSubmissionStatus(ctx context.Context, arg UpdateSubmissionStatusParams) error {
	_, err := q.db.Exec(ctx, updateSubmissionStatus, arg.ID, arg.Status)
	return err
}

// ListSubmissionsWithDetailsByAssignment — hand-written
const listSubmissionsWithDetailsByAssignment = `
SELECT
  s.id as submission_id,
  s.solution_url,
  s.status as submission_status,
  s.submitted_at,
  t.id as task_id,
  q.title as question_title,
  q.difficulty as question_difficulty,
  COALESCE(p.name, '') as mentee_name,
  s.mentee_id,
  f.id as feedback_id,
  COALESCE(f.comment, '') as feedback_comment,
  COALESCE(f.revision_required, false) as revision_required
FROM submissions s
JOIN assignment_tasks t ON t.id = s.assignment_task_id
JOIN questions q ON q.id = t.question_id
JOIN users ON s.mentee_id = users.id
LEFT JOIN user_profiles p ON p.user_id = s.mentee_id
LEFT JOIN mentor_feedbacks f ON f.submission_id = s.id
WHERE t.assignment_id = $1
ORDER BY s.submitted_at DESC
`

type SubmissionDetailRow struct {
	SubmissionID     pgtype.UUID          `json:"submission_id"`
	SolutionURL      *string              `json:"solution_url"`
	SubmissionStatus NullSubmissionStatus `json:"submission_status"`
	SubmittedAt      pgtype.Timestamptz   `json:"submitted_at"`
	TaskID           pgtype.UUID          `json:"task_id"`
	QuestionTitle    string               `json:"question_title"`
	QuestionDiff     string               `json:"question_difficulty"`
	MenteeName       string               `json:"mentee_name"`
	MenteeID         pgtype.UUID          `json:"mentee_id"`
	FeedbackID       pgtype.UUID          `json:"feedback_id"`
	FeedbackComment  string               `json:"feedback_comment"`
	RevisionRequired bool                 `json:"revision_required"`
}

func (q *Queries) ListSubmissionsWithDetailsByAssignment(ctx context.Context, assignmentID pgtype.UUID) ([]SubmissionDetailRow, error) {
	rows, err := q.db.Query(ctx, listSubmissionsWithDetailsByAssignment, assignmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SubmissionDetailRow
	for rows.Next() {
		var i SubmissionDetailRow
		if err := rows.Scan(
			&i.SubmissionID, &i.SolutionURL, &i.SubmissionStatus,
			&i.SubmittedAt, &i.TaskID, &i.QuestionTitle, &i.QuestionDiff,
			&i.MenteeName, &i.MenteeID, &i.FeedbackID, &i.FeedbackComment, &i.RevisionRequired,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}
