// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMenteeToBatch = `-- name: AddMenteeToBatch :exec
INSERT INTO batch_mentees (
  batch_id, mentee_id
) VALUES (
  $1, $2
)
`

type AddMenteeToBatchParams struct {
	BatchID  pgtype.UUID `json:"batch_id"`
	MenteeID pgtype.UUID `json:"mentee_id"`
}

func (q *Queries) AddMenteeToBatch(ctx context.Context, arg AddMenteeToBatchParams) error {
	_, err := q.db.Exec(ctx, addMenteeToBatch, arg.BatchID, arg.MenteeID)
	return err
}

const createBatch = `-- name: CreateBatch :one
INSERT INTO batches (
  name, mentor_id
) VALUES (
  $1, $2
)
RETURNING id, name, mentor_id, created_at, deleted_at
`

type CreateBatchParams struct {
	Name     string      `json:"name"`
	MentorID pgtype.UUID `json:"mentor_id"`
}

func (q *Queries) CreateBatch(ctx context.Context, arg CreateBatchParams) (Batch, error) {
	row := q.db.QueryRow(ctx, createBatch, arg.Name, arg.MentorID)
	var i Batch
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MentorID,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  email, password_hash, role
) VALUES (
  $1, $2, $3
)
RETURNING id, email, password_hash, role, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Email        string   `json:"email"`
	PasswordHash string   `json:"password_hash"`
	Role         UserRole `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createUserProfile = `-- name: CreateUserProfile :one
INSERT INTO user_profiles (
  user_id, name, avatar_url, bio
) VALUES (
  $1, $2, $3, $4
)
RETURNING user_id, name, avatar_url, bio
`

type CreateUserProfileParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	Name      string      `json:"name"`
	AvatarUrl *string     `json:"avatar_url"`
	Bio       *string     `json:"bio"`
}

func (q *Queries) CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, createUserProfile,
		arg.UserID,
		arg.Name,
		arg.AvatarUrl,
		arg.Bio,
	)
	var i UserProfile
	err := row.Scan(
		&i.UserID,
		&i.Name,
		&i.AvatarUrl,
		&i.Bio,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, role, created_at, updated_at, deleted_at FROM users
WHERE email = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, role, created_at, updated_at, deleted_at FROM users
WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserProfile = `-- name: GetUserProfile :one
SELECT user_id, name, avatar_url, bio FROM user_profiles
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetUserProfile(ctx context.Context, userID pgtype.UUID) (UserProfile, error) {
	row := q.db.QueryRow(ctx, getUserProfile, userID)
	var i UserProfile
	err := row.Scan(
		&i.UserID,
		&i.Name,
		&i.AvatarUrl,
		&i.Bio,
	)
	return i, err
}
